name: version

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  code-checks:
    if: "!contains(github.event.head_commit.message, 'chore: version packages')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-node
      - uses: ./.github/actions/check-code
